name: setup-op
description: Setup the 1Password CLI, op, on GitHub Actions runners
inputs:
  version:
    description: Version of the 1Password CLI to install
    required: false
    default: 2.18.0
  service-account-token:
    description: The 1Password service account token
    required: true
runs:
  using: node16
  main: dist/index.js
